### SignUp Failed - 1
POST {{server}}/signup
Accept: application/json
Content-Type: application/json

{
}

### SignUp Failed - 2
POST {{server}}/signup
Accept: application/json
Content-Type: application/json

{
    "loginId": "boki",
    "password": "1",
    "name": "이승복",
    "birthDate": "1992-05-30",
    "gender": "MAN",
    "email": "lsb530@naver.com"
}

### SignUp Success
POST {{server}}/signup
Accept: application/json
Content-Type: application/json

{
    "loginId": "boki",
    "password": "qwer1234!@",
    "name": "이승복",
    "birthDate": "1992-05-30",
    "gender": "MAN",
    "email": "lsb530@naver.com"
}

### SignUp Failed - Duplicated
POST {{server}}/signup
Accept: application/json
Content-Type: application/json

{
    "loginId": "boki",
    "password": "qwer1234!@",
    "name": "이승복",
    "birthDate": "1992-05-30",
    "gender": "MAN",
    "email": "lsb530@naver.com"
}

### Login Failed
POST {{server}}/login
Accept: application/json
Content-Type: application/json

{
    "loginId": "boki",
    "password": "qwer1234"
}

### Login Success with Admin
POST {{server}}/login
Accept: application/json
Content-Type: application/json

{
    "loginId": "admin",
    "password": "admin"
}

> {%
    client.global.set('access_token', response.body.data.accessToken)
%}

### Login Success with Staff
POST {{server}}/login
Accept: application/json
Content-Type: application/json

{
    "loginId": "staff",
    "password": "staff"
}

> {%
    client.global.set('access_token', response.body.data.accessToken)
%}

### Login Success with Member
POST {{server}}/login
Accept: application/json
Content-Type: application/json

{
    "loginId": "boki",
    "password": "qwer1234!@"
}

> {%
    client.global.set('access_token', response.body.data.accessToken)
%}

### Get MyInfo
GET {{server}}/info
Accept: application/json
Authorization: Bearer {{access_token}}

### Update MyInfo
PUT {{server}}/info
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "loginId": "boki",
    "password": "qwer1234!@",
    "name": "이승복2",
    "birthDate": "2000-05-30",
    "gender": "MAN",
    "email": "lsb530@naver.com"
}

### Create Post
POST {{server}}/posts
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "title": "점심고민",
    "content": "보통 점심때 뭐 먹나요?"
}

### Get Posts - Failed
GET {{server}}/posts
Accept: application/json

### Get Posts - Success(Only Admin)
GET {{server}}/posts
Accept: application/json
Authorization: Bearer {{access_token}}

### Get Post
@postId = 1
GET {{server}}/posts/{{postId}}
Accept: application/json
Authorization: Bearer {{access_token}}


### Delete Post
DELETE {{server}}/posts/{{postId}}
Accept: application/json
Authorization: Bearer {{access_token}}
