### SignUp Failed - 1
POST {{server}}/signup
Accept: application/json
Content-Type: application/json

{
}

### SignUp Failed - 2
POST {{server}}/signup
Accept: application/json
Content-Type: application/json

{
    "loginId": "boki",
    "password": "1",
    "name": "이승복",
    "birthDate": "1992-05-30",
    "gender": "MAN",
    "email": "lsb530@naver.com"
}

### SignUp Success
POST {{server}}/signup
Accept: application/json
Content-Type: application/json

{
    "loginId": "boki",
    "password": "qwer1234!@",
    "name": "이승복",
    "birthDate": "1992-05-30",
    "gender": "MAN",
    "email": "lsb530@naver.com"
}

### SignUp Failed - Duplicated
POST {{server}}/signup
Accept: application/json
Content-Type: application/json

{
    "loginId": "boki",
    "password": "qwer1234!@",
    "name": "이승복",
    "birthDate": "1992-05-30",
    "gender": "MAN",
    "email": "lsb530@naver.com"
}

### Login Failed
POST {{server}}/login
Accept: application/json
Content-Type: application/json

{
    "loginId": "boki",
    "password": "qwer1234"
}

### Login Success
POST {{server}}/login
Accept: application/json
Content-Type: application/json

{
    "loginId": "boki",
    "password": "qwer1234!@"
}

> {%
    client.global.set('access_token', response.body.data.accessToken)
%}

### Get MyInfo
GET {{server}}/info
Accept: application/json
Authorization: Bearer {{access_token}}

### Update MyInfo
PUT {{server}}/info
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "loginId": "boki",
    "password": "qwer1234!@",
    "name": "이승복2",
    "birthDate": "2000-05-30",
    "gender": "MAN",
    "email": "lsb530@naver.com"
}
