server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true # req, res에 인코딩 강제
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: rootroot
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        show_sql: false
        format_sql: true
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql: trace

jwt:
  secret: Y29kZS1ib2tpLnRpc3RvcnkuY29t
